# Ruff configuration
# See: https://docs.astral.sh/ruff/configuration/

target-version = "py310"
line-length = 100
src = ["verifflowcc", "tests"]
exclude = [".claude"]

[lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
    "S",   # flake8-bandit (security)
    "N",   # pep8-naming
    "TID", # flake8-tidy-imports
    "PTH", # flake8-use-pathlib
    "TCH", # flake8-type-checking
    "RUF", # Ruff-specific rules
]
ignore = [
    "E501",  # line too long, handled by black
    "B008",  # do not perform function calls in argument defaults
    "W191",  # indentation contains tabs
    "B904",  # Allow raising exceptions without from e, for cleaner exception handling
]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[lint.per-file-ignores]
"tests/*" = ["S101", "S603", "S607", "S108"]  # Allow assertions, subprocess usage in tests
"tests/integration/*" = ["S603", "S607"]  # Allow subprocess in integration tests
"verifflowcc/core/git_integration.py" = ["S603", "S607"]  # Git commands are safe in this module
