# Ruff configuration
# Moved from pyproject.toml to avoid validate-pyproject schema issues
# See: https://github.com/astral-sh/ruff/issues/11880

target-version = "py310"
line-length = 100
src = ["verifflowcc", "tests"]

[lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
    "S",   # flake8-bandit (security)
    "N",   # pep8-naming
    "TID", # flake8-tidy-imports
    "PTH", # flake8-use-pathlib
    "TCH", # flake8-type-checking
    "RUF", # Ruff-specific rules
]
ignore = ["S101"]  # Allow assert in tests

[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[lint.per-file-ignores]
"tests/*" = ["S101"]  # Allow assert in tests
"verifflowcc/cli.py" = ["B008"]  # Allow function calls in defaults (Typer pattern)
"verifflowcc/prompts/__init__.py" = ["S701"]  # Not rendering HTML, autoescape not needed
"verifflowcc/core/git_integration.py" = ["S603", "S607"]  # Allow subprocess calls for git operations
